language: ruby
rvm:
- 2.4.0
install:
- gem install bundler
- bundle install

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U vagrant

test:
  adapter: postgresql
  database: travis_ci_test
